name: Sample

on:
  push:
    paths:
      - ".github/**"
      - "dist/**"
      - "examples/**"

jobs:
  sample:
    name: Sample step
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: ./
        with:
          config-file: examples/demo1.yml
      - uses: ./
        with:
          config-file: examples/demo2.yml.gpg
          gpg-passphrase: secret stuff
      - if: ${{ matrix.os == 'windows-latest' }}
        name: sample
        run: |
          echo $env:DUMMY1_TOKEN
          echo $env:DUMMY2_TOKEN
          ls examples
      - if: ${{ matrix.os != 'windows-latest' }}
        name: sample
        run: |
          echo $DUMMY1_TOKEN
          echo $DUMMY2_TOKEN
          ls -al examples
